# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error_reporting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import validate_pb2 as validate_dot_validate__pb2
from . import common_v2_pb2 as common__v2__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='error_reporting.proto',
  package='error_reporting',
  syntax='proto3',
  serialized_options=b'\n\023io.moonsense.modelsB\024ErrorReportingProtosZ3moonsense.io/pkg/pb/error_reporting;error_reporting',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x65rror_reporting.proto\x12\x0f\x65rror_reporting\x1a\x17validate/validate.proto\x1a\x0f\x63ommon_v2.proto\"\\\n\x05\x46rame\x12\x10\n\x08\x66unction\x18\x01 \x01(\t\x12\x0e\n\x06module\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x0f\n\x07line_no\x18\x04 \x01(\x05\x12\x0e\n\x06\x63ol_no\x18\x05 \x01(\x05\"f\n\tException\x12\x15\n\x04type\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x12\x16\n\x05value\x18\x02 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x12*\n\nstacktrace\x18\x03 \x03(\x0b\x32\x16.error_reporting.Frame\"\xa4\x04\n\x0c\x45rrorMessage\x12\x16\n\x05title\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x12\x1a\n\ttimestamp\x18\x02 \x01(\x03\x42\x07\xfa\x42\x04\"\x02 \x00\x12\x37\n\x08platform\x18\x03 \x01(\x0e\x32\x19.v2.common.DevicePlatformB\n\xfa\x42\x07\x82\x01\x04\x10\x01 \x00\x12\x14\n\x0cmanufacturer\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t\x12\x12\n\nos_version\x18\x06 \x01(\t\x12>\n\x05level\x18\x07 \x01(\x0e\x32#.error_reporting.ErrorMessage.LevelB\n\xfa\x42\x07\x82\x01\x04\x10\x01 \x00\x12\x17\n\x0frelease_version\x18\x08 \x01(\t\x12\x15\n\rproguard_uuid\x18\t \x01(\t\x12-\n\texception\x18\n \x01(\x0b\x32\x1a.error_reporting.Exception\x12J\n\x0f\x61\x64\x64itional_tags\x18\x0b \x03(\x0b\x32\x31.error_reporting.ErrorMessage.AdditionalTagsEntry\x1a\x35\n\x13\x41\x64\x64itionalTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"L\n\x05Level\x12\x0b\n\x07INVALID\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\x01\x12\x08\n\x04INFO\x10\x02\x12\x0b\n\x07WARNING\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x12\t\n\x05\x46\x41TAL\x10\x05\x42`\n\x13io.moonsense.modelsB\x14\x45rrorReportingProtosZ3moonsense.io/pkg/pb/error_reporting;error_reportingb\x06proto3'
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,common__v2__pb2.DESCRIPTOR,])



_ERRORMESSAGE_LEVEL = _descriptor.EnumDescriptor(
  name='Level',
  full_name='error_reporting.ErrorMessage.Level',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FATAL', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=755,
  serialized_end=831,
)
_sym_db.RegisterEnumDescriptor(_ERRORMESSAGE_LEVEL)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='error_reporting.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='function', full_name='error_reporting.Frame.function', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='module', full_name='error_reporting.Frame.module', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filename', full_name='error_reporting.Frame.filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='line_no', full_name='error_reporting.Frame.line_no', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='col_no', full_name='error_reporting.Frame.col_no', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=176,
)


_EXCEPTION = _descriptor.Descriptor(
  name='Exception',
  full_name='error_reporting.Exception',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='error_reporting.Exception.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B\004r\002\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='error_reporting.Exception.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B\004r\002\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stacktrace', full_name='error_reporting.Exception.stacktrace', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=280,
)


_ERRORMESSAGE_ADDITIONALTAGSENTRY = _descriptor.Descriptor(
  name='AdditionalTagsEntry',
  full_name='error_reporting.ErrorMessage.AdditionalTagsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='error_reporting.ErrorMessage.AdditionalTagsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='error_reporting.ErrorMessage.AdditionalTagsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=700,
  serialized_end=753,
)

_ERRORMESSAGE = _descriptor.Descriptor(
  name='ErrorMessage',
  full_name='error_reporting.ErrorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='error_reporting.ErrorMessage.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B\004r\002\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='error_reporting.ErrorMessage.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B\004\"\002 \000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='platform', full_name='error_reporting.ErrorMessage.platform', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B\007\202\001\004\020\001 \000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='error_reporting.ErrorMessage.manufacturer', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='error_reporting.ErrorMessage.model', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='os_version', full_name='error_reporting.ErrorMessage.os_version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='error_reporting.ErrorMessage.level', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B\007\202\001\004\020\001 \000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='release_version', full_name='error_reporting.ErrorMessage.release_version', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proguard_uuid', full_name='error_reporting.ErrorMessage.proguard_uuid', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exception', full_name='error_reporting.ErrorMessage.exception', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='additional_tags', full_name='error_reporting.ErrorMessage.additional_tags', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ERRORMESSAGE_ADDITIONALTAGSENTRY, ],
  enum_types=[
    _ERRORMESSAGE_LEVEL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=831,
)

_EXCEPTION.fields_by_name['stacktrace'].message_type = _FRAME
_ERRORMESSAGE_ADDITIONALTAGSENTRY.containing_type = _ERRORMESSAGE
_ERRORMESSAGE.fields_by_name['platform'].enum_type = common__v2__pb2._DEVICEPLATFORM
_ERRORMESSAGE.fields_by_name['level'].enum_type = _ERRORMESSAGE_LEVEL
_ERRORMESSAGE.fields_by_name['exception'].message_type = _EXCEPTION
_ERRORMESSAGE.fields_by_name['additional_tags'].message_type = _ERRORMESSAGE_ADDITIONALTAGSENTRY
_ERRORMESSAGE_LEVEL.containing_type = _ERRORMESSAGE
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['Exception'] = _EXCEPTION
DESCRIPTOR.message_types_by_name['ErrorMessage'] = _ERRORMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'error_reporting_pb2'
  # @@protoc_insertion_point(class_scope:error_reporting.Frame)
  })
_sym_db.RegisterMessage(Frame)

Exception = _reflection.GeneratedProtocolMessageType('Exception', (_message.Message,), {
  'DESCRIPTOR' : _EXCEPTION,
  '__module__' : 'error_reporting_pb2'
  # @@protoc_insertion_point(class_scope:error_reporting.Exception)
  })
_sym_db.RegisterMessage(Exception)

ErrorMessage = _reflection.GeneratedProtocolMessageType('ErrorMessage', (_message.Message,), {

  'AdditionalTagsEntry' : _reflection.GeneratedProtocolMessageType('AdditionalTagsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ERRORMESSAGE_ADDITIONALTAGSENTRY,
    '__module__' : 'error_reporting_pb2'
    # @@protoc_insertion_point(class_scope:error_reporting.ErrorMessage.AdditionalTagsEntry)
    })
  ,
  'DESCRIPTOR' : _ERRORMESSAGE,
  '__module__' : 'error_reporting_pb2'
  # @@protoc_insertion_point(class_scope:error_reporting.ErrorMessage)
  })
_sym_db.RegisterMessage(ErrorMessage)
_sym_db.RegisterMessage(ErrorMessage.AdditionalTagsEntry)


DESCRIPTOR._options = None
_EXCEPTION.fields_by_name['type']._options = None
_EXCEPTION.fields_by_name['value']._options = None
_ERRORMESSAGE_ADDITIONALTAGSENTRY._options = None
_ERRORMESSAGE.fields_by_name['title']._options = None
_ERRORMESSAGE.fields_by_name['timestamp']._options = None
_ERRORMESSAGE.fields_by_name['platform']._options = None
_ERRORMESSAGE.fields_by_name['level']._options = None
# @@protoc_insertion_point(module_scope)
