# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: journey_feedback.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='journey_feedback.proto',
  package='journey_feedback',
  syntax='proto3',
  serialized_options=b'\n\'io.moonsense.models.v2.journey_feedbackB\025JourneyFeedbackProtosZ\"moonsense.io/pkg/pb/v2/journeys;v2',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16journey_feedback.proto\x12\x10journey_feedback\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n\rFraudFeedback\x12\x13\n\x0b\x66\x65\x65\x64\x62\x61\x63k_id\x18\x01 \x01(\t\x12\x10\n\x08is_fraud\x18\x02 \x01(\x08\x12/\n\x0breported_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0c\x66raud_reason\x18\x04 \x01(\t\"\x8c\x01\n\x12\x43hargebackFeedback\x12\x13\n\x0b\x66\x65\x65\x64\x62\x61\x63k_id\x18\x01 \x01(\t\x12\x15\n\ris_chargeback\x18\x02 \x01(\x08\x12/\n\x0breported_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x19\n\x11\x63hargeback_reason\x18\x04 \x01(\t\"\xa1\x01\n\x0fJourneyFeedback\x12\x12\n\njourney_id\x18\x01 \x01(\t\x12\x37\n\x0e\x66raud_feedback\x18\x03 \x01(\x0b\x32\x1f.journey_feedback.FraudFeedback\x12\x41\n\x13\x63hargeback_feedback\x18\x04 \x01(\x0b\x32$.journey_feedback.ChargebackFeedbackBd\n\'io.moonsense.models.v2.journey_feedbackB\x15JourneyFeedbackProtosZ\"moonsense.io/pkg/pb/v2/journeys;v2b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_FRAUDFEEDBACK = _descriptor.Descriptor(
  name='FraudFeedback',
  full_name='journey_feedback.FraudFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feedback_id', full_name='journey_feedback.FraudFeedback.feedback_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_fraud', full_name='journey_feedback.FraudFeedback.is_fraud', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reported_at', full_name='journey_feedback.FraudFeedback.reported_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fraud_reason', full_name='journey_feedback.FraudFeedback.fraud_reason', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=202,
)


_CHARGEBACKFEEDBACK = _descriptor.Descriptor(
  name='ChargebackFeedback',
  full_name='journey_feedback.ChargebackFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feedback_id', full_name='journey_feedback.ChargebackFeedback.feedback_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_chargeback', full_name='journey_feedback.ChargebackFeedback.is_chargeback', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reported_at', full_name='journey_feedback.ChargebackFeedback.reported_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chargeback_reason', full_name='journey_feedback.ChargebackFeedback.chargeback_reason', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=345,
)


_JOURNEYFEEDBACK = _descriptor.Descriptor(
  name='JourneyFeedback',
  full_name='journey_feedback.JourneyFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='journey_id', full_name='journey_feedback.JourneyFeedback.journey_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fraud_feedback', full_name='journey_feedback.JourneyFeedback.fraud_feedback', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chargeback_feedback', full_name='journey_feedback.JourneyFeedback.chargeback_feedback', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=509,
)

_FRAUDFEEDBACK.fields_by_name['reported_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CHARGEBACKFEEDBACK.fields_by_name['reported_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_JOURNEYFEEDBACK.fields_by_name['fraud_feedback'].message_type = _FRAUDFEEDBACK
_JOURNEYFEEDBACK.fields_by_name['chargeback_feedback'].message_type = _CHARGEBACKFEEDBACK
DESCRIPTOR.message_types_by_name['FraudFeedback'] = _FRAUDFEEDBACK
DESCRIPTOR.message_types_by_name['ChargebackFeedback'] = _CHARGEBACKFEEDBACK
DESCRIPTOR.message_types_by_name['JourneyFeedback'] = _JOURNEYFEEDBACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FraudFeedback = _reflection.GeneratedProtocolMessageType('FraudFeedback', (_message.Message,), {
  'DESCRIPTOR' : _FRAUDFEEDBACK,
  '__module__' : 'journey_feedback_pb2'
  # @@protoc_insertion_point(class_scope:journey_feedback.FraudFeedback)
  })
_sym_db.RegisterMessage(FraudFeedback)

ChargebackFeedback = _reflection.GeneratedProtocolMessageType('ChargebackFeedback', (_message.Message,), {
  'DESCRIPTOR' : _CHARGEBACKFEEDBACK,
  '__module__' : 'journey_feedback_pb2'
  # @@protoc_insertion_point(class_scope:journey_feedback.ChargebackFeedback)
  })
_sym_db.RegisterMessage(ChargebackFeedback)

JourneyFeedback = _reflection.GeneratedProtocolMessageType('JourneyFeedback', (_message.Message,), {
  'DESCRIPTOR' : _JOURNEYFEEDBACK,
  '__module__' : 'journey_feedback_pb2'
  # @@protoc_insertion_point(class_scope:journey_feedback.JourneyFeedback)
  })
_sym_db.RegisterMessage(JourneyFeedback)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
