# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='signal.proto',
  package='v2.signal',
  syntax='proto3',
  serialized_options=b'\n\035io.moonsense.models.v2.signalB\014SignalProtosZ$moonsense.io/pkg/pb/v2/signal;signal',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csignal.proto\x12\tv2.signal\"D\n\x02Os\x12\x1b\n\x13predicted_os_family\x18\x01 \x01(\t\x12!\n\x19predicted_os_family_score\x18\x02 \x01(\x01\x42S\n\x1dio.moonsense.models.v2.signalB\x0cSignalProtosZ$moonsense.io/pkg/pb/v2/signal;signalb\x06proto3'
)




_OS = _descriptor.Descriptor(
  name='Os',
  full_name='v2.signal.Os',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='predicted_os_family', full_name='v2.signal.Os.predicted_os_family', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predicted_os_family_score', full_name='v2.signal.Os.predicted_os_family_score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['Os'] = _OS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Os = _reflection.GeneratedProtocolMessageType('Os', (_message.Message,), {
  'DESCRIPTOR' : _OS,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:v2.signal.Os)
  })
_sym_db.RegisterMessage(Os)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
